name: BuildTest

on:
  workflow_call:


jobs:
  BuildTest:
    runs-on: 
      group: Default

    steps:   
    - name: Pre-Clean
      run: |
        cd ../
        rm -rf config/
        rm -rf eros_dev_app

    - name: Check out eros_dev_app
      uses: actions/checkout@v1
      with:
        repository: fastrobotics/eros_dev_app
        path: catkin_ws/src/eros_dev_app
        ref: master
    
    - name: Setup eros_dev_app
      run: |
        cd ../
        mv eros_dev_app/scenarios/dev/ config/
        rm -rf eros_dev_app/

    - uses: actions/checkout@v1
      with:
        path: catkin_ws/src/ros_hats

    - name: Check out eros
      uses: actions/checkout@v1
      with:
        repository: fastrobotics/eros
        path: catkin_ws/src/eros
        ref: master

    

    - name: Check Format
      run: |
        ./scripts/formatter.sh dry-run
        
    - name: Build Libraries & Binaries
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        rm -r -f build/ devel/
        catkin_make

    - name: Build Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make tests

    - name: Run Tests
      run: |
        cd ../../
        source /opt/ros/noetic/setup.bash
        catkin_make -j1 run_tests_ros_hats
        catkin_test_results build/test_results
      
    - name: Code Coverage
      run: |
        ./scripts/dev_tools.sh code_coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/coverage.xml
        badge: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md